package:
  name: "agiletools"
  version: "{{SCIENCE_TOOLS_TAG}}"

source:
  git_url: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
  git_rev: "{{SCIENCE_TOOLS_TAG}}"

build:
  number: 0
  script_env:
    - SCIENCE_TOOLS_TAG

requirements:
  host:
    - python==3.7.6
    - cmake 3.*
    - make
    - xorg-libxpm
    - binutils 2.35
    - openssl
    - cfitsio==3.470
    - zlib==1.2.11
    - gsl==2.6
  run:
    - python==3.7.6
    - cfitsio==3.470
    - zlib==1.2.11
    - gsl==2.6


about:
  home: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework.'
  description: |
    The software environment for Agilepy.
  dev_url: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
