{% set name = "Agilepy" %}
{% set version = "0.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/AGILESCIENCE/Agilepy

build:
  number: 0

requirements:
  host:
    - astropy
    - pip
    - git
    - python
    - pyyaml
    - numpy
  run:
    - astropy >=1.3
    - gammapy >=0.7.0
    - healpy
    - matplotlib >=1.5.0
    - numpy >=1.10.0
    - python >=3.7,<3.8.0a0
    - pyyaml
    - scipy >=0.14
about:
  home:

