{% set name = "Agilepy" %}
{% set version = "0.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/AGILESCIENCE/Agilepy

build:
  number: 0

requirements:
  host:
    - git
    - python
    - cfitsio 
    - root
    - zlib
    - gsl
    - pyyaml
  run:
    - astropy
    - gammapy
    - healpy
    - opencv
    - matplotlib
    - pyyaml
    - scipy
about:
  home:
