{% set name = "Agilepy" %}
{% set version = "0.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/AGILESCIENCE/Agilepy

build:
  number: 0

requirements:
  host:
    - python 3.7
    - cfitsio
    - root
    
    - zlib
    - gsl
    - pyyaml
  run:
    - python 3.7
    - cfitsio 
    - root

    - pyyaml
