package:
  name: "agilepy-environment"
  version: "{{SCIENCE_TOOLS_TAG}}"

source:
  git_url: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
  git_rev: "{{SCIENCE_TOOLS_TAG}}"

build:
  number: 0
  script_env:
    - SCIENCE_TOOLS_TAG

requirements:
  host:
    - python==3.7.6
    - cfitsio==3.470
    - root==6.18.04
    - zlib==1.2.11
    - gsl==2.6
  run:
    - python==3.7.6
    - cfitsio==3.470
    - root==6.18.04
    - astropy==4.0
    - plotly==4.12.0
    - psutil==5.7.0
    - matplotlib==3.1.3
    - pandas==1.0.1
    - ipympl==0.5.7
    - numpy==1.18.1
    - scipy==1.4.1
    - sphinx==2.3.1
    - sphinx_rtd_theme==0.4.3
    - pyyaml==5.3
    - regions==0.4
    - pytest-cov==2.8.1
    - python-kaleido=0.0.3


about:
  home: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework.'
  description: |
    The software environment for Agilepy.
  dev_url: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
