{% set name = "Agilepy" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/AGILESCIENCE/Agilepy
  git_rev: v1.0.0

build:
  number: 0

requirements:
  host:
    - python 3.7
    - cfitsio
    - root
    - zlib
    - gsl
    - pyyaml
  run:
    - python 3.7
    - astropy
    - plotly
    - matplotlib
    - pandas
    - numpy
    - scipy
    - cfitsio 
    - root
    - sphinx
    - sphinx_rtd_theme
    - pyyaml

