{% set agilepy_version = "v1.0.0" %}
{% set package_version = "1.0.0" %}
{% set build_number = 0 %}

package:
  name: "agilepy"
  version: {{ package_version }}

source:
  git_url: https://github.com/AGILESCIENCE/Agilepy
  # git_rev: {{ agilepy_version }}

build:
  number: {{ build_number }}

requirements:
  host:
    - python 3.7
    - cfitsio
    - root
    - zlib
    - gsl
  run:
    - python 3.7
    - astropy
    - plotly
    - matplotlib
    - pandas
    - numpy
    - scipy
    - cfitsio 
    - root
    - sphinx
    - sphinx_rtd_theme
    - pyyaml


about:
  home: https://github.com/AGILESCIENCE/Agilepy
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework'
  description: |
    A python wrapper around the AGILE science tools.
  dev_url: https://github.com/AGILESCIENCE/Agilepy
  doc_url: https://agilepy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/AGILESCIENCE/Agilepy/blob/master/docs/source/index.rst
