{% set agilepy_version = "v1.0.0" %}
{% set package_version = "1.0.0.beta" %}
{% set build_number = 0 %}

package:
  name: "agilepy"
  version: {{ package_version }}

source:
  git_url: https://github.com/AGILESCIENCE/Agilepy
  # git_rev: {{ agilepy_version }}

build:
  number: {{ build_number }}

requirements:
  host:
    - python==3.7.6
    - cfitsio==3.470
    - root==6.18.04
    - zlib==1.2.11
    - gsl==2.6
  run:
    - python 3.7
    - astropy==4.0
    - plotly==4.5.0
    - matplotlib==3.1.3
    - pandas==1.0.1
    - numpy==1.18.1
    - scipy==1.4.1
    - cfitsio==3.470
    - root==6.18.04
    - sphinx==2.3.1
    - sphinx_rtd_theme==0.4.3
    - pyyaml==5.3
    - regions==0.4
    - pytest-cov==2.8.1


about:
  home: https://github.com/AGILESCIENCE/Agilepy
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework'
  description: |
    A python wrapper around the AGILE science tools.
  dev_url: https://github.com/AGILESCIENCE/Agilepy
  doc_url: https://agilepy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/AGILESCIENCE/Agilepy/blob/master/docs/source/index.rst
