{% set name = "Agilepy" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: /__w/Agilepy/Agilepy

build:
  number: 0

requirements:
  host:
    - python==3.7.6
    - cfitsio==3.470
    - root==6.18.04
    - zlib==1.2.11
    - gsl==2.6
  run:
    - python 3.7
    - astropy==4.0
    - plotly==4.5.0
    - matplotlib==3.1.3
    - pandas==1.0.1
    - numpy==1.18.1
    - scipy==1.4.1
    - cfitsio==3.470 
    - root==6.18.04
    - sphinx==2.3.1
    - sphinx_rtd_theme==0.4.3
    - pyyaml==5.3
    - regions==0.4


about:
  home: https://github.com/AGILESCIENCE/Agilepy
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework'
  description: |
    A python wrapper around the AGILE science tools.
  dev_url: https://github.com/AGILESCIENCE/Agilepy
  doc_url: https://agilepy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/AGILESCIENCE/Agilepy/blob/master/docs/source/index.rst
