{% set name = "Agilepy" %}
{% set version = "1.0.0-beta" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: /__w/Agilepy/Agilepy

build:
  number: 0

requirements:
  host:
    - python 3.7
    - cfitsio
    - root
    - zlib
    - gsl
  run:
    - python 3.7
    - astropy
    - plotly
    - matplotlib
    - pandas
    - numpy
    - scipy
    - cfitsio
    - root
    - sphinx
    - sphinx_rtd_theme
    - pyyaml
    - regions==0.4


about:
  home: https://github.com/AGILESCIENCE/Agilepy
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework'
  description: |
    A python wrapper around the AGILE science tools.
  dev_url: https://github.com/AGILESCIENCE/Agilepy
  doc_url: https://agilepy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/AGILESCIENCE/Agilepy/blob/master/docs/source/index.rst
