package:
  name: "agilepy"
  version: "{{PACKAGE_TAG}}"

source:
  git_url: https://github.com/AGILESCIENCE/Agilepy
  git_rev: "{{AGILEPY_TAG}}"

build:
  number: 0

requirements:
  host:
    - python==3.7.6
    - astropy==4.0
    - plotly==4.12.0
    - psutil==5.7.0
    - matplotlib==3.1.3
    - pandas==1.0.1
    - ipympl==0.5.7
    - numpy==1.19
    - scipy==1.4.1
    - sphinx==2.3.1
    - sphinx_rtd_theme==0.4.3
    - pyyaml==5.3
    - regions==0.4
    - pytest-cov==2.8.1
    - python-kaleido==0.0.3
  run:
    - python==3.7.6
    - astropy==4.0
    - plotly==4.12.0
    - psutil==5.7.0
    - matplotlib==3.1.3
    - pandas==1.0.1
    - ipympl==0.5.7
    - numpy==1.19
    - scipy==1.4.1
    - sphinx==2.3.1
    - sphinx_rtd_theme==0.4.3
    - pyyaml==5.3
    - regions==0.4
    - pytest-cov==2.8.1
    - python-kaleido==0.0.3


about:
  home: https://github.com/AGILESCIENCE/Agilepy
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework'
  description: |
    A python wrapper around the AGILE science tools.
  dev_url: https://github.com/AGILESCIENCE/Agilepy
  doc_url: https://agilepy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/AGILESCIENCE/Agilepy/blob/master/docs/source/index.rst
